CREATE TABLE IF NOT EXISTS sensor_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  `time` DATETIME NOT NULL,
  temp VARCHAR(32) NOT NULL,
  tds VARCHAR(32) NOT NULL,
  status VARCHAR(16) NOT NULL,
  mode VARCHAR(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS app_mode (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  mode VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO app_mode (id, mode) VALUES (1, 'non');
