CREATE TABLE IF NOT EXISTS sensor_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  time DATETIME NOT NULL,
  temp VARCHAR(32) NOT NULL,
  tds VARCHAR(32) NOT NULL,
  status VARCHAR(16) NOT NULL,
  mode VARCHAR(16) NOT NULL
);

CREATE TABLE IF NOT EXISTS sensor_latest (
  id INT NOT NULL PRIMARY KEY,
  time DATETIME NOT NULL,
  temp VARCHAR(32) NOT NULL,
  tds VARCHAR(32) NOT NULL,
  status VARCHAR(16) NOT NULL,
  mode VARCHAR(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;